import type {
  Company,
  CompanyStats,
  CurrencyEnum,
  LevelEnum,
  SalaryRecord,
  SourceEnum,
} from '@/types/salary';

// Mock data uses full-rupee or full-dollar integers for readability.
// Production data should use smallest units (paise/cents) instead.

type MakeRecordInput = Omit<SalaryRecord, 'total_compensation'>;

const makeRecord = (input: MakeRecordInput): SalaryRecord => ({
  ...input,
  total_compensation: input.base_salary + input.bonus + input.stock,
});

export const SALARY_RECORDS: SalaryRecord[] = [
  // Edge case: experience_years = 1 (junior)
  makeRecord({
    id: 'sal_001',
    company: 'google',
    company_slug: 'google',
    company_display: 'Google India',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 1800000,
    bonus: 150000,
    stock: 300000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.82,
    submitted_at: '2026-05-10T10:15:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_002',
    company: 'google',
    company_slug: 'google',
    company_display: 'Google India',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 4,
    base_salary: 3200000,
    bonus: 350000,
    stock: 900000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.88,
    submitted_at: '2026-04-21T09:10:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_003',
    company: 'google',
    company_slug: 'google',
    company_display: 'Google India',
    role: 'Senior Software Engineer',
    level_standardized: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 7,
    base_salary: 4500000,
    bonus: 600000,
    stock: 1400000,
    source: 'AI_INFERRED',
    confidence_score: 0.72,
    submitted_at: '2026-03-11T12:30:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_004',
    company: 'amazon',
    company_slug: 'amazon',
    company_display: 'Amazon India',
    role: 'SDE I',
    level_standardized: 'SDE_I',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 2,
    base_salary: 1500000,
    bonus: 100000,
    stock: 250000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.86,
    submitted_at: '2026-05-03T08:00:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_005',
    company: 'amazon',
    company_slug: 'amazon',
    company_display: 'Amazon India',
    role: 'SDE II',
    level_standardized: 'SDE_II',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2800000,
    bonus: 250000,
    stock: 700000,
    source: 'SCRAPED',
    confidence_score: 0.65,
    submitted_at: '2026-02-10T14:20:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_006',
    company: 'amazon',
    company_slug: 'amazon',
    company_display: 'Amazon India',
    role: 'SDE III',
    level_standardized: 'SDE_III',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 9,
    base_salary: 4200000,
    bonus: 500000,
    stock: 1600000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.8,
    submitted_at: '2026-01-22T11:05:00Z',
    is_verified: true,
  }),
  // Edge case: PRINCIPAL level
  makeRecord({
    id: 'sal_007',
    company: 'microsoft',
    company_slug: 'microsoft',
    company_display: 'Microsoft India',
    role: 'Principal Engineer',
    level_standardized: 'PRINCIPAL',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 15,
    base_salary: 8500000,
    bonus: 1500000,
    stock: 5000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.9,
    submitted_at: '2026-04-12T13:45:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_008',
    company: 'microsoft',
    company_slug: 'microsoft',
    company_display: 'Microsoft India',
    role: 'Software Engineer',
    level_standardized: 'IC4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2600000,
    bonus: 250000,
    stock: 650000,
    source: 'SCRAPED',
    confidence_score: 0.62,
    submitted_at: '2026-02-18T09:55:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_009',
    company: 'microsoft',
    company_slug: 'microsoft',
    company_display: 'Microsoft India',
    role: 'Senior Software Engineer',
    level_standardized: 'IC5',
    location: 'Pune',
    currency: 'INR',
    experience_years: 8,
    base_salary: 4200000,
    bonus: 450000,
    stock: 1200000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.85,
    submitted_at: '2026-03-26T17:20:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_010',
    company: 'meta',
    company_slug: 'meta',
    company_display: 'Meta India',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Remote',
    currency: 'USD',
    experience_years: 5,
    base_salary: 165000,
    bonus: 20000,
    stock: 40000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.9,
    submitted_at: '2026-05-15T16:00:00Z',
    is_verified: true,
  }),
  // Edge case: very large total_compensation (>= 4,00,00,000)
  makeRecord({
    id: 'sal_011',
    company: 'meta',
    company_slug: 'meta',
    company_display: 'Meta India',
    role: 'Staff Software Engineer',
    level_standardized: 'STAFF',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 12,
    base_salary: 20000000,
    bonus: 5000000,
    stock: 20000000,
    source: 'AI_INFERRED',
    confidence_score: 0.7,
    submitted_at: '2026-01-30T10:40:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_012',
    company: 'flipkart',
    company_slug: 'flipkart',
    company_display: 'Flipkart Internet Pvt Ltd',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2400000,
    bonus: 250000,
    stock: 600000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.86,
    submitted_at: '2026-02-25T12:00:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_013',
    company: 'flipkart',
    company_slug: 'flipkart',
    company_display: 'Flipkart Internet Pvt Ltd',
    role: 'Senior Software Engineer',
    level_standardized: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 7,
    base_salary: 3600000,
    bonus: 400000,
    stock: 900000,
    source: 'SCRAPED',
    confidence_score: 0.6,
    submitted_at: '2026-03-04T10:10:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_014',
    company: 'meesho',
    company_slug: 'meesho',
    company_display: 'Meesho',
    role: 'Backend Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2600000,
    bonus: 200000,
    stock: 800000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.84,
    submitted_at: '2026-05-19T07:40:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_015',
    company: 'meesho',
    company_slug: 'meesho',
    company_display: 'Meesho',
    role: 'Senior Backend Engineer',
    level_standardized: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 8,
    base_salary: 3800000,
    bonus: 350000,
    stock: 1000000,
    source: 'SCRAPED',
    confidence_score: 0.63,
    submitted_at: '2026-01-18T18:30:00Z',
    is_verified: false,
  }),
  // Edge case: very high stock (>= 1,00,00,000)
  makeRecord({
    id: 'sal_016',
    company: 'nvidia',
    company_slug: 'nvidia',
    company_display: 'NVIDIA India',
    role: 'Graphics Software Engineer',
    level_standardized: 'L6',
    location: 'Pune',
    currency: 'INR',
    experience_years: 11,
    base_salary: 6000000,
    bonus: 800000,
    stock: 12000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.87,
    submitted_at: '2026-04-01T06:20:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_017',
    company: 'nvidia',
    company_slug: 'nvidia',
    company_display: 'NVIDIA India',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 3200000,
    bonus: 300000,
    stock: 900000,
    source: 'SCRAPED',
    confidence_score: 0.66,
    submitted_at: '2026-02-07T09:00:00Z',
    is_verified: false,
  }),
  // Edge case: bonus = 0 and stock = 0
  makeRecord({
    id: 'sal_018',
    company: 'tcs',
    company_slug: 'tcs',
    company_display: 'Tata Consultancy Services',
    role: 'SDE I',
    level_standardized: 'SDE_I',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 2,
    base_salary: 700000,
    bonus: 0,
    stock: 0,
    source: 'CONTRIBUTOR',
    confidence_score: 0.92,
    submitted_at: '2026-01-05T08:10:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_019',
    company: 'tcs',
    company_slug: 'tcs',
    company_display: 'Tata Consultancy Services',
    role: 'Senior Software Engineer',
    level_standardized: 'L4',
    location: 'Pune',
    currency: 'INR',
    experience_years: 6,
    base_salary: 1200000,
    bonus: 80000,
    stock: 0,
    source: 'SCRAPED',
    confidence_score: 0.58,
    submitted_at: '2026-02-01T07:15:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_020',
    company: 'infosys',
    company_slug: 'infosys',
    company_display: 'Infosys',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Mysuru',
    currency: 'INR',
    experience_years: 3,
    base_salary: 900000,
    bonus: 60000,
    stock: 0,
    source: 'CONTRIBUTOR',
    confidence_score: 0.9,
    submitted_at: '2026-03-09T10:05:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_021',
    company: 'wipro',
    company_slug: 'wipro',
    company_display: 'Wipro',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 3,
    base_salary: 850000,
    bonus: 50000,
    stock: 0,
    source: 'SCRAPED',
    confidence_score: 0.57,
    submitted_at: '2026-03-12T09:30:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_022',
    company: 'razorpay',
    company_slug: 'razorpay',
    company_display: 'Razorpay',
    role: 'Frontend Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2100000,
    bonus: 200000,
    stock: 500000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.83,
    submitted_at: '2026-05-01T12:25:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_023',
    company: 'razorpay',
    company_slug: 'razorpay',
    company_display: 'Razorpay',
    role: 'Senior Frontend Engineer',
    level_standardized: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 7,
    base_salary: 3200000,
    bonus: 350000,
    stock: 900000,
    source: 'SCRAPED',
    confidence_score: 0.61,
    submitted_at: '2026-02-14T11:10:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_024',
    company: 'zepto',
    company_slug: 'zepto',
    company_display: 'Zepto',
    role: 'Backend Engineer',
    level_standardized: 'L4',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2200000,
    bonus: 180000,
    stock: 700000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.81,
    submitted_at: '2026-05-06T09:45:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_025',
    company: 'zepto',
    company_slug: 'zepto',
    company_display: 'Zepto',
    role: 'Senior Backend Engineer',
    level_standardized: 'L5',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 6,
    base_salary: 3100000,
    bonus: 250000,
    stock: 900000,
    source: 'SCRAPED',
    confidence_score: 0.6,
    submitted_at: '2026-03-18T15:00:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_026',
    company: 'uber',
    company_slug: 'uber',
    company_display: 'Uber India',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 3000000,
    bonus: 250000,
    stock: 900000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.86,
    submitted_at: '2026-04-05T10:10:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_027',
    company: 'uber',
    company_slug: 'uber',
    company_display: 'Uber India',
    role: 'Senior Software Engineer',
    level_standardized: 'L5',
    location: 'Remote',
    currency: 'USD',
    experience_years: 8,
    base_salary: 175000,
    bonus: 25000,
    stock: 50000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.88,
    submitted_at: '2026-04-28T09:00:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_028',
    company: 'salesforce',
    company_slug: 'salesforce',
    company_display: 'Salesforce India',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2400000,
    bonus: 250000,
    stock: 700000,
    source: 'SCRAPED',
    confidence_score: 0.64,
    submitted_at: '2026-01-25T13:30:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_029',
    company: 'adobe',
    company_slug: 'adobe',
    company_display: 'Adobe India',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Delhi',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2600000,
    bonus: 200000,
    stock: 600000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.84,
    submitted_at: '2026-04-07T08:20:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_030',
    company: 'oracle',
    company_slug: 'oracle',
    company_display: 'Oracle India',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2100000,
    bonus: 180000,
    stock: 500000,
    source: 'SCRAPED',
    confidence_score: 0.6,
    submitted_at: '2026-02-12T10:30:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_031',
    company: 'atlassian',
    company_slug: 'atlassian',
    company_display: 'Atlassian',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2900000,
    bonus: 250000,
    stock: 900000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.87,
    submitted_at: '2026-05-09T09:05:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_032',
    company: 'atlassian',
    company_slug: 'atlassian',
    company_display: 'Atlassian',
    role: 'Senior Software Engineer',
    level_standardized: 'L5',
    location: 'Remote',
    currency: 'USD',
    experience_years: 9,
    base_salary: 190000,
    bonus: 30000,
    stock: 70000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.89,
    submitted_at: '2026-05-12T10:00:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_033',
    company: 'sap',
    company_slug: 'sap',
    company_display: 'SAP Labs India',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 3,
    base_salary: 1400000,
    bonus: 100000,
    stock: 200000,
    source: 'SCRAPED',
    confidence_score: 0.59,
    submitted_at: '2026-02-20T12:15:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_034',
    company: 'ibm',
    company_slug: 'ibm',
    company_display: 'IBM India',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Pune',
    currency: 'INR',
    experience_years: 3,
    base_salary: 1300000,
    bonus: 90000,
    stock: 150000,
    source: 'SCRAPED',
    confidence_score: 0.56,
    submitted_at: '2026-01-28T09:30:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_035',
    company: 'paytm',
    company_slug: 'paytm',
    company_display: 'Paytm',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Delhi',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2000000,
    bonus: 150000,
    stock: 400000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.8,
    submitted_at: '2026-03-22T11:35:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_036',
    company: 'phonepe',
    company_slug: 'phonepe',
    company_display: 'PhonePe',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2300000,
    bonus: 200000,
    stock: 500000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.82,
    submitted_at: '2026-03-30T08:15:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_037',
    company: 'swiggy',
    company_slug: 'swiggy',
    company_display: 'Swiggy',
    role: 'Backend Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2400000,
    bonus: 200000,
    stock: 700000,
    source: 'SCRAPED',
    confidence_score: 0.62,
    submitted_at: '2026-02-06T07:45:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_038',
    company: 'zomato',
    company_slug: 'zomato',
    company_display: 'Zomato',
    role: 'Backend Engineer',
    level_standardized: 'L4',
    location: 'Delhi',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2100000,
    bonus: 150000,
    stock: 600000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.79,
    submitted_at: '2026-04-09T10:50:00Z',
    is_verified: true,
  }),
  // Edge case: experience_years = 20 (senior)
  makeRecord({
    id: 'sal_039',
    company: 'amazon',
    company_slug: 'amazon',
    company_display: 'Amazon India',
    role: 'Principal Engineer',
    level_standardized: 'PRINCIPAL',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 20,
    base_salary: 11000000,
    bonus: 2000000,
    stock: 8000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.93,
    submitted_at: '2026-05-02T06:50:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_040',
    company: 'inmobi',
    company_slug: 'inmobi',
    company_display: 'InMobi',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2200000,
    bonus: 200000,
    stock: 500000,
    source: 'SCRAPED',
    confidence_score: 0.6,
    submitted_at: '2026-01-17T09:20:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_041',
    company: 'accenture',
    company_slug: 'accenture',
    company_display: 'Accenture',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Pune',
    currency: 'INR',
    experience_years: 3,
    base_salary: 1000000,
    bonus: 70000,
    stock: 0,
    source: 'SCRAPED',
    confidence_score: 0.55,
    submitted_at: '2026-03-02T11:00:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_042',
    company: 'nvidia',
    company_slug: 'nvidia',
    company_display: 'NVIDIA India',
    role: 'Staff Engineer',
    level_standardized: 'STAFF',
    location: 'Remote',
    currency: 'USD',
    experience_years: 13,
    base_salary: 210000,
    bonus: 35000,
    stock: 90000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.9,
    submitted_at: '2026-05-11T14:10:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_043',
    company: 'google',
    company_slug: 'google',
    company_display: 'Google India',
    role: 'Staff Software Engineer',
    level_standardized: 'L6',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 10,
    base_salary: 7000000,
    bonus: 1200000,
    stock: 3500000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.88,
    submitted_at: '2026-04-14T09:35:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_044',
    company: 'microsoft',
    company_slug: 'microsoft',
    company_display: 'Microsoft India',
    role: 'Staff Engineer',
    level_standardized: 'STAFF',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 11,
    base_salary: 6500000,
    bonus: 900000,
    stock: 2500000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.87,
    submitted_at: '2026-03-16T16:45:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_045',
    company: 'tcs',
    company_slug: 'tcs',
    company_display: 'Tata Consultancy Services',
    role: 'Tech Lead',
    level_standardized: 'L5',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 9,
    base_salary: 1800000,
    bonus: 150000,
    stock: 0,
    source: 'SCRAPED',
    confidence_score: 0.59,
    submitted_at: '2026-01-20T12:00:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_046',
    company: 'infosys',
    company_slug: 'infosys',
    company_display: 'Infosys',
    role: 'Tech Lead',
    level_standardized: 'L5',
    location: 'Pune',
    currency: 'INR',
    experience_years: 9,
    base_salary: 1700000,
    bonus: 120000,
    stock: 0,
    source: 'SCRAPED',
    confidence_score: 0.58,
    submitted_at: '2026-02-27T10:10:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_047',
    company: 'wipro',
    company_slug: 'wipro',
    company_display: 'Wipro',
    role: 'Tech Lead',
    level_standardized: 'L5',
    location: 'Delhi',
    currency: 'INR',
    experience_years: 10,
    base_salary: 1600000,
    bonus: 100000,
    stock: 0,
    source: 'SCRAPED',
    confidence_score: 0.56,
    submitted_at: '2026-03-07T09:55:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_048',
    company: 'razorpay',
    company_slug: 'razorpay',
    company_display: 'Razorpay',
    role: 'Engineering Manager',
    level_standardized: 'L6',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 11,
    base_salary: 5000000,
    bonus: 700000,
    stock: 1800000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.85,
    submitted_at: '2026-05-20T09:15:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_049',
    company: 'meta',
    company_slug: 'meta',
    company_display: 'Meta India',
    role: 'Software Engineer',
    level_standardized: 'L5',
    location: 'Remote',
    currency: 'USD',
    experience_years: 7,
    base_salary: 160000,
    bonus: 20000,
    stock: 45000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.86,
    submitted_at: '2026-04-20T07:00:00Z',
    is_verified: true,
  }),
  // Edge case: company display name is exactly 42 characters (table layout)
  makeRecord({
    id: 'sal_050',
    company: 'a-very-long-company-name-for-table-layouts',
    company_slug: 'a-very-long-company-name-for-table-layouts',
    company_display: 'A Very Long Company Name For Table Layouts',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 6,
    base_salary: 2400000,
    bonus: 200000,
    stock: 600000,
    source: 'AI_INFERRED',
    confidence_score: 0.68,
    submitted_at: '2026-04-02T11:40:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_051',
    company: 'google',
    company_slug: 'google',
    company_display: 'Google India',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Delhi',
    currency: 'INR',
    experience_years: 2,
    base_salary: 1700000,
    bonus: 120000,
    stock: 250000,
    source: 'SCRAPED',
    confidence_score: 0.6,
    submitted_at: '2026-01-12T06:30:00Z',
    is_verified: false,
  }),
  makeRecord({
    id: 'sal_052',
    company: 'microsoft',
    company_slug: 'microsoft',
    company_display: 'Microsoft India',
    role: 'Software Engineer',
    level_standardized: 'IC4',
    location: 'Remote',
    currency: 'USD',
    experience_years: 6,
    base_salary: 150000,
    bonus: 15000,
    stock: 35000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.88,
    submitted_at: '2026-05-13T12:20:00Z',
    is_verified: true,
  }),
  makeRecord({
    id: 'sal_053',
    company: 'amazon',
    company_slug: 'amazon',
    company_display: 'Amazon India',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 3100000,
    bonus: 300000,
    stock: 800000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.87,
    submitted_at: '2026-05-08T09:45:00Z',
    is_verified: true,
  }),
  // Edge case: single-record company for testing 1-record scenarios
  makeRecord({
    id: 'sal_054',
    company: 'startupco',
    company_slug: 'startupco',
    company_display: 'StartupCo',
    role: 'Senior Software Engineer',
    level_standardized: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 6,
    base_salary: 2500000,
    bonus: 200000,
    stock: 600000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.85,
    submitted_at: '2026-04-15T10:00:00Z',
    is_verified: true,
  }),
];

export const CONVERSION_RATES = {
  INR_TO_USD: 0.012,
  USD_TO_INR: 83.5,
} as const;

const COMPANY_METADATA: Record<string, Partial<Company>> = {
  google: {
    industry: 'Internet & Software',
    headquarters: 'Bengaluru, Karnataka',
    founded_year: 1998,
    headcount_range: '10,000+ employees',
    website: 'google.com',
    rating: 4.2,
    review_count: 9,
  },
  amazon: {
    industry: 'E-commerce & Cloud',
    headquarters: 'Bengaluru, Karnataka',
    founded_year: 1994,
    headcount_range: '10,000+ employees',
    website: 'amazon.in',
    rating: 3.8,
    review_count: 12,
  },
  microsoft: {
    industry: 'Software & Cloud Services',
    headquarters: 'Hyderabad, Telangana',
    founded_year: 1975,
    headcount_range: '10,000+ employees',
    website: 'microsoft.com',
    rating: 4.4,
    review_count: 15,
  },
  startupco: {
    industry: 'Financial Technology',
    headquarters: 'Bengaluru, Karnataka',
    founded_year: 2021,
    headcount_range: '11–50 employees',
    website: 'startupco.in',
    rating: 4.0,
    review_count: 3,
  },
  'a-very-long-company-name-for-table-layouts': {
    industry: 'Systems Engineering',
    headquarters: 'Mumbai, Maharashtra',
    founded_year: 2010,
    headcount_range: '501–1,000 employees',
    website: 'longcompanyname.com',
    rating: 3.5,
    review_count: 2,
  },
};

export const COMPANIES: Company[] = Array.from(
  SALARY_RECORDS.reduce((map, record) => {
    if (!map.has(record.company_slug)) {
      const meta = COMPANY_METADATA[record.company_slug] || {};
      map.set(record.company_slug, {
        id: record.company_slug,
        name: record.company_display,
        slug: record.company_slug,
        normalized_name: record.company,
        ...meta,
      });
    }
    return map;
  }, new Map<string, Company>()).values()
);

export const getCompanyBySlug = (slug: string): Company | undefined =>
  COMPANIES.find((company) => company.slug === slug);

export const getSalariesByCompanySlug = (slug: string): SalaryRecord[] =>
  SALARY_RECORDS.filter((record) => record.company_slug === slug);

const ALL_LEVELS: LevelEnum[] = [
  'L3',
  'L4',
  'L5',
  'L6',
  'SDE_I',
  'SDE_II',
  'SDE_III',
  'STAFF',
  'PRINCIPAL',
  'IC4',
  'IC5',
];

const initializeLevelDistribution = (): Record<LevelEnum, number> =>
  ALL_LEVELS.reduce(
    (acc, level) => {
      acc[level] = 0;
      return acc;
    },
    {} as Record<LevelEnum, number>
  );

const median = (values: number[]): number => {
  if (values.length === 0) {
    return 0;
  }
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  if (sorted.length % 2 === 0) {
    return (sorted[mid - 1] + sorted[mid]) / 2;
  }
  return sorted[mid];
};

export const computeCompanyStats = (records: SalaryRecord[]): CompanyStats => {
  const level_distribution = initializeLevelDistribution();

  if (records.length === 0) {
    return {
      median_total_compensation: 0,
      min_tc: 0,
      max_tc: 0,
      record_count: 0,
      level_distribution,
    };
  }

  const totals = records.map((record) => record.total_compensation);
  const min_tc = Math.min(...totals);
  const max_tc = Math.max(...totals);

  for (const record of records) {
    level_distribution[record.level_standardized] += 1;
  }

  return {
    median_total_compensation: median(totals),
    min_tc,
    max_tc,
    record_count: records.length,
    level_distribution,
  };
};

export type {
  Company,
  CompanyStats,
  CurrencyEnum,
  LevelEnum,
  SalaryRecord,
  SourceEnum,
};
